#ifndef IS_LVALUE_FUNCTION_HPP
#define IS_LVALUE_FUNCTION_HPP

namespace easytype
{

namespace function
{

template<typename T>
class IsLValueFunction;

// Pointer to member function with 0 parameters
template<typename R, typename C >class IsLValueFunction<R ( C::*)( ) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::*)( ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const)( ) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const )( ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* volatile )( ) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* volatile )( ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const volatile )( ) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const volatile )( ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::*)( ) const &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::*)( ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const)( ) const &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const )( ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* volatile )( ) const &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* volatile )( ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const volatile )( ) const &>:public easytype::basis::TrueType{};
template<typename R, typename C >class IsLValueFunction<R ( C::* const volatile )( ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 1 parameters
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::*)( p1) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::*)( p1 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const)( p1) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const )( p1 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* volatile )( p1) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* volatile )( p1 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const volatile )( p1) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const volatile )( p1 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::*)( p1) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::*)( p1 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const)( p1) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const )( p1 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* volatile )( p1) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* volatile )( p1 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const volatile )( p1) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1>class IsLValueFunction<R ( C::* const volatile )( p1 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 2 parameters
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::*)( p1 , p2) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::*)( p1 , p2 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const)( p1 , p2) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const )( p1 , p2 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* volatile )( p1 , p2) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* volatile )( p1 , p2 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const volatile )( p1 , p2) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::*)( p1 , p2) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::*)( p1 , p2 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const)( p1 , p2) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const )( p1 , p2 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* volatile )( p1 , p2) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* volatile )( p1 , p2 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const volatile )( p1 , p2) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 3 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::*)( p1 , p2 , p3) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::*)( p1 , p2 , p3) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 4 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 5 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 6 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 7 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 8 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 9 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 10 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 11 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 12 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 13 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 14 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) const &>:public easytype::basis::TrueType{};

// Pointer to member function with 15 parameters
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::*)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const)( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15) const &>:public easytype::basis::TrueType{};
template<typename R, typename C , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( C::* const volatile )( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) const &>:public easytype::basis::TrueType{};

// Type function with 0 parameters
template<typename R >class IsLValueFunction<R ( ) &>:public easytype::basis::TrueType{};
template<typename R >class IsLValueFunction<R ( ...) &>:public easytype::basis::TrueType{};
template<typename R >class IsLValueFunction<R ( ) const &>:public easytype::basis::TrueType{};
template<typename R >class IsLValueFunction<R ( ...) const &>:public easytype::basis::TrueType{};

// Type function with 1 parameters
template<typename R , typename p1>class IsLValueFunction<R ( p1 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1>class IsLValueFunction<R ( p1 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1>class IsLValueFunction<R ( p1 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1>class IsLValueFunction<R ( p1 ...) const &>:public easytype::basis::TrueType{};

// Type function with 2 parameters
template<typename R , typename p1 , typename p2>class IsLValueFunction<R ( p1 , p2 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2>class IsLValueFunction<R ( p1 , p2 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2>class IsLValueFunction<R ( p1 , p2 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2>class IsLValueFunction<R ( p1 , p2 ...) const &>:public easytype::basis::TrueType{};

// Type function with 3 parameters
template<typename R , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( p1 , p2 , p3 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( p1 , p2 , p3 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( p1 , p2 , p3 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3>class IsLValueFunction<R ( p1 , p2 , p3 ...) const &>:public easytype::basis::TrueType{};

// Type function with 4 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( p1 , p2 , p3 , p4 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( p1 , p2 , p3 , p4 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( p1 , p2 , p3 , p4 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4>class IsLValueFunction<R ( p1 , p2 , p3 , p4 ...) const &>:public easytype::basis::TrueType{};

// Type function with 5 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 ...) const &>:public easytype::basis::TrueType{};

// Type function with 6 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 ...) const &>:public easytype::basis::TrueType{};

// Type function with 7 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 ...) const &>:public easytype::basis::TrueType{};

// Type function with 8 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 ...) const &>:public easytype::basis::TrueType{};

// Type function with 9 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 ...) const &>:public easytype::basis::TrueType{};

// Type function with 10 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10 ...) const &>:public easytype::basis::TrueType{};

// Type function with 11 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11 ...) const &>:public easytype::basis::TrueType{};

// Type function with 12 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12 ...) const &>:public easytype::basis::TrueType{};

// Type function with 13 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13 ...) const &>:public easytype::basis::TrueType{};

// Type function with 14 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14 ...) const &>:public easytype::basis::TrueType{};

// Type function with 15 parameters
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ) const &>:public easytype::basis::TrueType{};
template<typename R , typename p1 , typename p2 , typename p3 , typename p4 , typename p5 , typename p6 , typename p7 , typename p8 , typename p9 , typename p10, typename p11, typename p12, typename p13, typename p14, typename p15>class IsLValueFunction<R ( p1 , p2 , p3 , p4 , p5 , p6 , p7 , p8 , p9 , p10, p11, p12, p13, p14, p15 ...) const &>:public easytype::basis::TrueType{};

// Not an Left Value Function
template<typename T>
class IsLValueFunction:public easytype::basis::FalseType{};	
	
}	
	
}
#endif



